version: "3.3"
services:
    mongo:
        container_name: mongo
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - data-volume:/data/db
        networks:
            - internal
volumes:
    data-volume:

networks:
    internal:
      external: true
